### ISSUE TITLE
Output PEM public keys from openssh keys

### ISSUE THREAD

**Issue by mattbradbury** [Leo1003/rust-osshkeys#2]
I'd like to not have to run this command on the command-line.  The privkey is the default OpenSSH 'ssh-keygen' output. 

ssh-keygen -m pem -e -f <privkey_file>

I'm not very in depth on how all the different formats work together and how to convert them, otherwise I'd do it myself and submit a PR.

Looking for this style output:
-----BEGIN RSA PUBLIC KEY-----
MIIBCgKCAQEA1oKy6WEBYp044NxRurUz+X44xW48Y6b90D7huLaJHry2yqckTxRT
mTSArFSzjrxikH0KeFaWBGNQPmhtI9+plDhJyV8S79QnMYSrZ2xD4ulqk1/SSDz6
94+Vja6i2DcHw0WBXX8VWe4PS1OCkgg3tcimOa8ZxUx6WSyqM/WFsavSSUu6lB6b
IKzOwuOxu4gsBcfFnaihKe9BhuEr7JK2vMjs8uCDDFZLuL5sPMGsOebGfyB5S/0f
oBJSut2eR2LLt9Pjq8xv5jwXXYqJkJdk5OB7IDuFiLWU3dFbtpZrW20LoYcJjtcS
+XDH4aOdGFUPhxAv5P9Oa8gV2yjOGz9uVwIDAQAB
-----END RSA PUBLIC KEY-----

Thanks.

**Comment by Leo1003** [comment]
I will try to use OpenSSL to generate the output before I find/develop a suitable PEM library on all platforms.
Sorry for the late reply. I am a bit of busy recently, and may need some times to work on it.

**Comment by Leo1003** [comment]
On the latest 0.4 version, this feature has been implemented.
