### ISSUE TITLE
Please release 0.4.1 to pull in ed25519-dalek 1.0

### ISSUE THREAD

**Issue by pianohacker** [Leo1003/rust-osshkeys#3]
I love this project (it's kept me from the hell of scripting `ssh-keygen`), but I currently have to build from git to avoid a build failure due to ed25519-dalek 1.0.0-pre3... and git dependencies aren't allowed in published crates.

@Leo1003 , could you please publish 0.4.1?

**Comment by Leo1003** [comment]
I am working on this today.
Sorry for you waiting on this.

**Comment by Leo1003** [comment]
v0.4.1 released. The dependencies are pulled in now.

**Comment by pianohacker** [comment]
Thank you! https://crates.io/crates/secretgarden just got published. Thank you for making this crate, it made this part of my project trivial :)
