### ISSUE TITLE
Replace nom_pem with other dependencies

### ISSUE THREAD

**Issue by Leo1003** [Leo1003/rust-osshkeys#7]
Since the most used PEM crate [pem](https://crates.io/crates/pem) do not support handling PEM message with header. Therefore, this repository use [nom_pem](https://crates.io/crates/nom_pem) to handle the PEM format.

Here are the reasons to replace it:
1. The crate is unmaintained
    - The Github repository is even 404
2. The base64 in the crate is implemented by itself, hence, reduce the code reusability...
3. I don't want to introduce a whole parsing framework(nom) just to parse the PEM format

**Comment by fenollp** [comment]
pem v2 claims to support reading headers https://github.com/jcreekmore/pem-rs/issues/36

**Comment by Leo1003** [comment]
This is a great news. Thanks for telling me that!

**Comment by fenollp** [comment]
Sure :) How can I help move this forward?
